Description: If you want to create a PDF from scratch, you can use Dhek to design a template based on a blank document, to define layout areas (commons elements, e.g. Where to write static title on all generated documents).
PageDimension: Page dimension
NumberPage: Number of page
A2_P: A2 (portrait)
A2_L: A2 (landscape)
A3_P: A3 (portrait)
A3_L: A3 (landscape)
A4_P: A4 (portrait)
A4_L: A4 (landscape)
A5_P: A5 (portrait)
A5_L: A5 (landscape)