Description: Si vous souhaitez créer un document PDF de zéro, vous pouvez utiliser Dhek pour concevoir un modèle basé sur un document vierge, pour placer des zones de présentation (éléments communs, ex : Où placer un titre statique pour tous les documents).
PageDimension: Dimensions page
NumberPage: Nombre de page
A2_P: A2 (portrait)
A2_L: A2 (paysage)
A3_P: A3 (portrait)
A3_L: A3 (paysage)
A4_P: A4 (portrait)
A4_L: A4 (paysage)
A5_P: A5 (portrait)
A5_L: A5 (paysage)