File: File
OpenPDF: Open PDF
LoadMappings: Load mappings
SaveMappings: Save mappings
EnableOverlap: Enable overlapping areas
Previous: Previous
Next: Next
Remove: Remove
RemoveTooltip: Remove selected areas
Name: Name
Type: Type
Areas: Areas
PdfFilter: PDF File
Open: Open
Cancel: Cancel
JsonFilter: JSON File
Save: Save
Choose: Choose
ChooseJSON: Choose a JSON file
MainTitle: Dhek - PDF templating
Apply: Apply
ApplyTooltip: Apply area changes
Value: Value
Yes: Yes
No: No
ConfirmQuit: Do you want to save changes?
Index: Index
SplashOpenPDFFile: 1. Open a PDF File
SplashEdit: 2. Edit areas to be filled over choosen document
SplashSave: 3. Save areas as a separate template file
SplashCopy: 4. Copy PDF by filling data according template
DontSave: Don't save
DuplicationModePopup: Drag &amp; drop to duplicate
DrawHelp: Click to draw, ALT + drag&drop to duplicate
DupHelp: Drag&drop area to duplicate it
SelectionHelp meta@String: Click to start selection, release to finalize. #{meta} + click to update selection.
JsonFormatError msg@String: Invalid mapping file: #{msg}
NormalModeTooltip: Draw areas over document
SelectionModeTooltip: Select several areas, apply bulk operations.
OpenBlank: Open blank document
OpenBlankTooltip: Open an in-memory blank document to create a template from scratch
BlankDocument: *Blank Document*
NoArea: No area was defined. Template file cannot be saved.
ZoomInTooltip: Zoom In
ZoomOutTooltip: Zoom Out
ApplidokTooltip: Open Applidok service
PreviousPageTooltip: Go back to previous page
NextPageTooltip: Go to next page
MagneticForce: Magnetic force
FontCacheInit: Initializing cache for system fonts. It may take a while. Please wait…