File: File
OpenPDF: Open PDF
LoadMappings: Load mappings
SaveMappings: Save mappings
EnableOverlap: Enable overlapping areas
Previous: Previous
Next: Next
Remove: Remove
Name: Name
Type: Type
Areas: Areas
PdfFilter: PDF File
Open: Open
Cancel: Cancel
JsonFilter: JSON File
Save: Save
Choose: Choose
ChooseJSON: Choose a JSON file
MainTitle: Dhek - PDF templating
Apply: Apply
Value: Value
Yes: Yes
No: No
ConfirmQuit: Do you want to save changes?
Index: Index
SplashOpenPDFFile: 1. Open a PDF File
SplashEdit: 2. Edit areas to be filled over choosen document
SplashSave: 3. Save areas as a separate template file
SplashCopy: 4. Copy PDF by filling data according template
DontSave: Don't save
DuplicationModePopup: Drag &amp; drop to duplicate
DuplicationModeStatus: ALT: Duplication mode. Drag & drop existing area to duplicate it where wanted.
ModeHelp: Click to draw, ALT + drag&drop to duplicate