File: Fichier
OpenPDF: Ouvrir PDF
LoadMappings: Charger modèle
SaveMappings: Sauvegarder modèle
EnableOverlap: Autoriser le chevauchement des zones
Previous: Précédent
Next: Suivant
Remove: Supprimer
RemoveTooltip: Supprimer les zones sélectionnées
Name: Nom
Type: Type
Areas: Zones
PdfFilter: Fichier PDF
Open: Ouvrir
Cancel: Annuler
JsonFilter: Fichier JSON
Save: Enregistrer
Choose: Choisir
ChooseJSON: Choisir un fichier JSON
MainTitle: Dhek - Création de modèle PDF
Apply: Appliquer
ApplyTooltip: Appliquer les changements sur la zone
Value: Valeur
Yes: Oui
No: Non
ConfirmQuit: Voulez-vous enregistrer les modifications ?
Index: Index
SplashOpenPDFFile: 1. Ouvrir un fichier PDF
SplashEdit: 2. Editer des zones à remplir sur le document
SplashSave: 3. Sauvegarder les zones comme modèle
SplashCopy: 4. Copier le PDF par remplissage selon le modèle
DontSave: Ne pas enregister
DuplicationModePopup: Glissé-déposé pour dupliquer
DrawHelp: Cliquer pour dessiner, ALT + glissé-déposé pour dupliquer
DupHelp: Glisser-déposer une zone pour la dupliquer
SelectionHelp meta@String: Cliquer pour débuter une sélection, relâcher pour terminer. #{meta} + clic pour modifier la sélection.
JsonFormatError msg@String: Format du fichier modèle incorrect: #{msg}
NormalModeTooltip: Dessiner les zones sur le document
SelectionModeTooltip: Sélectionner plusieurs zones, modifications groupées.
OpenBlank: Ouvrir un document vierge
OpenBlankTooltip: Ouvrir un document vierge, pour créer un modèle de zéro.
BlankDocument: *Document vierge*
NoArea: Aucune zone n'a été ajoutée. Le fichier modèle ne peut être sauvegardé.
ZoomInTooltip: Augmenter l'échelle du document
ZoomOutTooltip: Diminuer l'échelle du document
ApplidokTooltip: Ouvrir le service Applidok
PreviousPageTooltip: Aller à la page précédente
NextPageTooltip: Aller à la page suivante
