File: Fichier
OpenPDF: Ouvrir PDF
LoadMappings: Charger modèle
SaveMappings: Sauvegarder modèle
EnableOverlap: Autoriser le chevauchement des zones
Previous: Précédent
Next: Suivant
Remove: Supprimer
Name: Nom
Type: Type
Areas: Zones
PdfFilter: Fichier PDF
Open: Ouvrir
Cancel: Annuler
JsonFilter: Fichier JSON
Save: Sauvegarder
Choose: Choisir
ChooseJSON: Choisir un fichier JSON
MainTitle: Dhek - Création de modèle PDF
Apply: Appliquer
Value: Valeur
Yes: Oui
No: Non
Confirm: Le modèle a été modifié. Voulez vous quitter sans sauvegarder ces modifications ?
Index: Index
SplashOpenPDFFile: 1. Ouvrir un fichier PDF
SplashEdit: 2. Editer des zones à remplir sur le document
SplashSave: 3. Sauvegarder les zones comme modèle
SplashCopy: 4. Copier le PDF par remplissage selon le modèle